### ISSUE TITLE
Release TODO list

### ISSUE THREAD

**Issue by AleksandarDev** [RainbowDashDC/wpGitter#2]
### Bugs

- [ ] Navigating from login page to home page causes error request.
- [ ] Hitting TAB when entered username causes login request instead of focusing on password
- [ ] Allow access to account message is too high
- [ ] Conversation header is too long, it should be trimmed (currently jumps to next line)
- [ ] On conversations list page, clicking on header (left side) will trigger `goBack` command when there is no back button
- [ ] Sent messages don't show up on client

#### Error messages:

- [ ] ```APPHOST9601: Can’t load <https://ws.gitter.im/faye?message=%5B%7B%22channel%22%3A%22%2Fmeta%2Fhandshake%22%2C%22version%22%3A%221.0%22%2C%22supportedConnectionTypes%22%3A%5B%22websocket%22%2C%22eventsource%22%2C%22long-polling%22%2C%22cross-origin-long-polling%22%2C%22callback-polling%22%5D%2C%22id%22%3A%221%22%2C%22ext%22%3A%7B%22token%22%3A%22e12051f61a52bfa4496a525a6ef55dc50092c007%22%7D%7D%5D&jsonp=__jsonp1__>. An app can’t load remote web content in the local context.```

- [ ] ```APPHOST9601: Can’t load <https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700>. An app can’t load remote web content in the local context.```

- [ ] ```CSS3111: @font-face encountered unknown error.```

### Features

- [ ] Logout
- [ ] Private/Public conversation indicator
- [ ] Settings

### Design

- [ ] Loading messages indicator inside conversation

**Comment by RainbowDashDC** [comment]
Thank you for taking the time to figure some of this out! Really means alot.

**Comment by RainbowDashDC** [comment]
Regarding the TAB login context, I don't think *we* have control over that.

**Comment by AleksandarDev** [comment]
This list is so that we have all issues on one place instead of creating multiple issues. I will take a look into these issues today after work and let you know what I'm working on.

**Comment by RainbowDashDC** [comment]
I think it's important to express the UI state (the design) is crucial to me, I'm personally not a fan of the win phone UI.

**Comment by AleksandarDev** [comment]
It can stay the way it looks now. Important is to use WinJS grid and StackPanel that supports virtualization and bindings so that it doesn't slow down the scrolling.
